import avatarIcon from '../assets/img/avatar.png';
import image from '../assets/img/BigBook.png'

import { BookItem, User } from './interfaces';

export const user: User = {
  name: 'Иван',
  avatar: avatarIcon,
};

export const books: BookItem[] = [
  {
    id: 1,
    image: [''],
    stars: 0,
    category: 'business',
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    author: 'Адитья Бхаргава, 2019',
    reserve: false,
  },
  {
    id: 2,
    image: [image],
    stars: 4,
    category: 'business',
    title: 'Грокаем алгоритмы. Иллюстрированное',
    author: 'Адитья Бхаргава, 2019',
    reserve: false,
  },
  {
    id: 3,
    image: [image, image, image, image, image],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы.',
    author: 'Адитья Бхаргава, 2019',
    reserve: true,
    data: '03.05',
  },
  {
    id: 4,
    image: [image],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    author: 'Адитья Бхаргава, 2019',
    reserve: false,
  },
  {
    id: 5,
    image: [image],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    author: 'Адитья Бхаргава, Патрик Нимейер, 2019',
    reserve: true,
    data: '07.09',
  },
  {
    id: 6,
    image: [''],
    category: 'business',
    stars: 0,
    title: 'Грокаем алгоритмы. Иллюстрированное',
    author: 'Адитья Бхаргава, Патрик Нимейер, 2019',
    reserve: true,
    data: '23.04',
  },
  {
    id: 7,
    image: [image],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы.',
    author: 'Адитья Бхаргава, Патрик Нимейер, 2019',
    reserve: false,
  },
  {
    id: 8,
    image: [image],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    author: 'Адитья Бхаргава, Патрик Нимейер, 2019',
    reserve: false,
  },
  {
    id: 9,
    image: [image],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    author: 'Адитья Бхаргава, 2019',
    reserve: false,
  },
  {
    id: 10,
    image: [''],
    category: 'business',
    stars: 4,
    title: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    author: 'Адитья Бхаргава, 2019',
    reserve: false,
  },
];
